### ISSUE TITLE
Where are the settings set with this new version?

### ISSUE THREAD

**Issue by ghibble** [rcgroot/open-gpstracker-ng#18]
I have been using Open GPS Tracker for a few weeks and just discovered the new NG version.  I like the feel a lot better but I have not found where to change the settings.  I am wanting to switch miles to km.

Thanks
Geoff

**Comment by rcgroot** [comment]
It only uses the device locale, e.g. miles in en/us and km in en/uk.

Edit: although that might not be included in the alpha store version. That one could use an update....
