### ISSUE TITLE
Track naming

### ISSUE THREAD

**Issue by johnjohndoe** [rcgroot/open-gpstracker-ng#19]
The naming of recorded tracks recently changed - I noticed it at August 7, 2018.

# Former track naming
Before tracks where named by using the recording date in reverse format such as: `Track 2018-08-06 18:38`. When the track is exported to Google Drive using the [open-gpstracker-exporter](https://github.com/rcgroot/open-gpstracker-exporter) a file named `track_64_Track 2018-08-06 1838` is created.

# Current track naming
The new track naming uses the Weekday and the time of the day. The above example would become `Monday afternoon` and the exported file would be named `track_64_Monday afternoon`.

Here is a screenshot of the app and a file listing showing both cases - names are highlighted in blue:

![screenshot](https://user-images.githubusercontent.com/144518/44197090-ff1d7e00-a13d-11e8-91b2-889a8b91d89f.png) ![files](https://user-images.githubusercontent.com/144518/44197563-41938a80-a13f-11e8-8866-a04c43b2c109.png)

# Proposal
I would very much appreciate to see the track naming being reverted to the old style or a least being configurable. The weekday/daytime naming makes it very cumbersome to find files, sort and organize them. I have not found a reason for the change but I would be interested to hear about it.
For convenience please also add the file extension `.gpx` when exporting the files which has been the case in earlier version of the [open-gpstracker](https://github.com/rcgroot/open-gpstracker) app.

**Comment by pbpb** [comment]
I agree with johnjohndoe.

I would also add that there is no reason to interpose the track naming between "start tracking" and going to the tracking.  There is no need for a track name if the track will not later be saved, and this just adds an unnecessary step before one gets to the tracking map.

**Comment by johnjohndoe** [comment]
I had a look at the implementation the other day. I found that the track name is generated via [`NameGenerator#generateName()`](https://github.com/rcgroot/open-gpstracker-ng/blob/develop/studio/features/src/main/java/nl/sogeti/android/gpstracker/ng/features/trackedit/NameGenerator.kt#L44). This class could be swapped out with an alternative implementation. In the settings users then can pick their preference.

**Comment by pbpb** [comment]
Thanks for the info, essentially answering both questions.  I'm not ready to start hacking it, but maybe M. Groot would consider it in his new implementation.

**Comment by rcgroot** [comment]
The date is already presented in the track-card. It has not sense to duplicate that in the track name. The file names created by the exporter are composed of the trackId and trackName, but that could just as well become a combination of date and track name to help organizing the files.

I'll need to check on that remark about the file extension.

**Comment by johnjohndoe** [comment]
@rcgroot Thank you for your response. I agree with you that the track-card can **display** both the weekday name and the date.
With regards to the exporter I prefer the **reverse date** as the pattern for the file name as it has been in earlier versions of the app.

**Comment by johnjohndoe** [comment]
One remark with regards to the **date displaying**. Very recent tracks at the top of the list do **not** show the date but instead something like `6 days ago`.

**Comment by rcgroot** [comment]
The file names will become something like:
`track_25_2018-03-26T11:12_maandag morning.gpx`
build up such:
track trackId reverseDate time trackName gpxExtension

**Comment by johnjohndoe** [comment]
Nice to hear that you include the reverse date again :+1: 
Out of curiosity, what is your use case to prepend `track_25_` and prepend `_maandag morning`?

**Comment by rcgroot** [comment]
track -> make is clear it is ogt-export in my folder of other files
25 -> unique id per track per device, useful for cross references
date -> 2018-03-26T11:12
maandag morning -> human readable user editable track title
.gpx -> extension

**Comment by johnjohndoe** [comment]
### With regards to the `unique id per track per device`

Did you notice somewhen that two devices produce the same file name such as `2018-03-26T11:12_maandag morning.gpx` when you start tracking at the exact same time? I can imagine that this is possible.
However, the `unique id` would not help with that since it could be the same number on two devices if I use them in parallel all the time.

Therefore, if you need a unique device identifier I would recommend to use an identifier which is [provided by Android](https://medium.com/@ssaurel/how-to-retrieve-an-unique-id-to-identify-android-devices-c40080e04fa4).

### Track naming
It would be great if user can decide themselves which naming convention is used for the track export. This could be an app setting.

**Comment by rcgroot** [comment]
The number just references the database entry of the database the track was stored. It is unique with regard to the single database table instance, which is fine.
