### ISSUE TITLE
Build error in Android studio 2.1.1.0

### ISSUE THREAD

**Issue by lohriialo** [rcgroot/open-gpstracker-ng#3]
Import project to Android studio 2.1.1.0, following warning:
"This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system"

Build/Run project, following error:
"Error:(41, 34) java: package android.support.annotation does not exist"
"Error:(42, 34) java: package android.support.v4.content does not exist"
"Error:(55, 13) java: cannot find symbol
  symbol:   class IGPSLoggerServiceRemote
  location: class nl.sogeti.android.gpstracker.integration.ServiceManager"

**Comment by johnjohndoe** [comment]
Please note that you need to select the `studio/` subfolder. It contains the Gradle wrapper which should be recognized by Android Studio. I was able to build the latest commit both via Gradle wrapper at the command line and in Android Studio.
