### ISSUE TITLE
Gradle warnings

### ISSUE THREAD

**Issue by shrenuj** [rcgroot/open-gpstracker-ng#4]
Warning:(54, 24) Application namespace for attribute bind:state will be ignored.
@control\ControlHandler.java
this line "@BindingAdapter({"bind:state"}) "

@recording\RecordingHandler.java
Warning:(38, 24) Application namespace for attribute bind:isRecording will be ignored.
this line    "@BindingAdapter({"bind:isRecording"}) "

**Comment by rcgroot** [comment]
Fixed in abf07ec812df6bd91d6520775a3db05faee63e8f
