### ISSUE TITLE
Possible to distribute app via F-Droid?

### ISSUE THREAD

**Issue by collectorgeneral** [rcgroot/open-gpstracker-ng#5]
This app looks really interesting, is it possible to release this on F-Droid? I do not have play store on my device, I mostly use F-Droid. Since your app is open source, is it possible for you to list your app on F-Droid?

There is an Issue #2 , which is closed and I can see that the person referenced F-Droid. However there were no details provided as to why the issue was renamed or closed.

**Comment by IzzySoft** [comment]
If there are no intentions to put it on F-Droid, maybe at least attach the `.apk` files to their corresponding `releases/` here at Github? I could then pick them up automatically and serve them via [my F-Droid repo](https://android.izzysoft.de/repo).

**Comment by rcgroot** [comment]
I like that release/ part, I do appreciatie it at other Github projects.

Created issue as #7

**Comment by IzzySoft** [comment]
So it's about to come? Please let us know when it's there :)

**Comment by stpr-dev** [comment]
@IzzySoft Thanks for volunteering to host the app! If you and @rcgroot  manage to set it up and distribute using your repo that would be great too!

**Comment by IzzySoft** [comment]
@collectorgeneral as soon as it's available here and I know about it, it will be available in my repo. We have to wait for @rcgroot to attach it with the next `releases/` – which I guess he's planning to do.
