### ISSUE TITLE
Streaming to HTTP Server

### ISSUE THREAD

**Issue by jagauthier** [rcgroot/open-gpstracker-ng#6]
This is a carry over issue from the legacy application.  POSTing to an HTTP address for streaming the data just doesn't work.  Nothing is ever communicated to the HTTP server.

**Comment by rcgroot** [comment]
Seeing as this is feature for tech-savvy users I don't think I will add this to this app, but spin it off as an add-on app. That way it can have some proper configurations and diagnostics without cluttering the recording app.

**Comment by rcgroot** [comment]
Repo claimed at https://github.com/rcgroot/open-gpstracker-stream
